
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://antoncbn.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id to track your visitors

google-tracking-id: "UA-78812731-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "AntonCabon"
title: "Antoncabon"
description: "Blog and website of Anton Cabon, blogging mainly for tech. Opinions expressed are mine."
keywords: "anton, cbn, personal, jekyll, theme, cabon, antoncabon, blog, github"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/terminal.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Welcome to Anton Cabon Blog"

me-img: "/img/antoncbn.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "antoncabon"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2005 - 2011"
    description: "Estate Manager!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2012 - Today"
    description: "Started Blogging"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "antoncabon@yandex.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Anton Cabon is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, Anton likes to eat pempek Palembang."
author_blurb_image: "/img/antoncabon2.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/antoncabon"
  - title: "twitter"
    url: "https://twitter.com/antoncabon"
  - title: "github"
    url: "https://github.com/antoncbn"
  - title: "paypal"
    url: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=Y58F7K7QLBCUE&lc=ZA&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
